### ISSUE TITLE
Just curious if I am able to make something like Vim out of this?

### ISSUE THREAD

**Issue by Joe23232** [mackwic/colored#104]
Hi I would like to know if I am able to make something like `vim` out of this crate?

**Comment by Horgix** [comment]
@Joe23232 I'm not sure what you mean here. This library only provides coloring of terminal output (text).

You will _definitely_ not be able to create a full blown text editor with that crate only. You can however probably use it to colorize text here and there if you were to build one!

Does that answer your question? :slightly_smiling_face:

**Comment by Raj2032** [comment]
@Horgix Yes it does, thanks mate :)

**Comment by Horgix** [comment]
You're welcome :relaxed:

**Comment by Raj2032** [comment]
By the way @Horgix is it still being maintained this project?

**Comment by Horgix** [comment]
@Raj2032 I believe it somehow is, and maybe be more in the future :slightly_smiling_face: Saw @kurtlawrence merge/close quite a bunch of things recently, and @mackwic mentioned to me recently that he may pick up the project maintenance more actively again (if that becomes the reality or not is of course up to him :slightly_smiling_face: )

**Comment by mackwic** [comment]
So: yes this repository is still maintained. ;)

**Comment by Joe23232** [comment]
AH right thanks mate :)
