### ISSUE TITLE
I'm having issue with powershell

### ISSUE THREAD

**Issue by mrquantumoff** [mackwic/colored#110]
So, I have compiled my app for windows and I see this.

![image](https://user-images.githubusercontent.com/36820091/173596372-d2ea9e82-54d2-488a-88fc-5830d27be453.png)

As you see [clap's](https://crates.io/crates/clap) coloured output is ok, but mine is strange, does anybody know what to do with this?

**Comment by mrquantumoff** [comment]
I made it work by adding a few lines of code in the main function 

```rust
fn main() {
 #[cfg(windows)] {
      let _varname = colored::control::set_virtual_terminal(true).unwrap_or(());
  }
}
```

**Comment by kurtlawrence** [comment]
Thanks @mrquantumoff. If you would like to add some documentation in the readme as a PR that would help heaps.
