### ISSUE TITLE
Parse Color from ANSI string

### ISSUE THREAD

**Issue by d47081** [mackwic/colored#187]
Does `colored` crate provide any build-in method for parse some raw `String` contain ANSI
to foreground/background `Color` objects (e.g. as vector members) ? 
* _Thoughts convert these values collected into RGBa format, by `to_fg_str` / `to_bg_str`, then use with GTK `TextTag`_ 

Thanks for your work!

**Comment by kurtlawrence** [comment]
`colored` does not. It is explicitly designed to focus on formatting. I maintain https://docs.rs/cansi/latest/cansi/ which does what you want.
