### ISSUE TITLE
Support global toggle via env variable

### ISSUE THREAD

**Issue by mackwic** [mackwic/colored#2]
Via popular demand, the user should be able to force turning ON or OFF `colored` via an environment variable.

I consider using `RUST_NOCOLOR` and `RUST_FORCECOLOR`, but I would like to have the opinion of other implementers on the matter and see if we can coordinate a little.

This is the tracking issue.

**Comment by mackwic** [comment]
Very interesting discussion on the user-rust forum: https://users.rust-lang.org/t/introducing-colored-the-most-simple-way-to-add-colors-in-your-term/4968/21?u=mackwic

The winning spec seems to becomes http://bixense.com/clicolors/ which is already implemented by some popular softwares.

**Comment by mackwic** [comment]
Should be resolved by 62f6e83 (tag `v1.1.0`). I'll keep this open in the case, and close it if no one makes noise in some time.

**Comment by mackwic** [comment]
Ref to [this comment](https://github.com/ogham/rust-ansi-term/issues/10#issuecomment-225765856) it seems like a good idea to toggle the should-colorize-auto-detection-by-env via a feature flag (always or never), so that lib consumer would be able to take control of this behavior.

Also, exposing setters on this behavior could help

**Comment by mackwic** [comment]
fixed by #10

**Comment by lukehsiao** [comment]
Would it be possible to also support the [`NO_COLOR`](https://no-color.org/) spec?
