### ISSUE TITLE
Add color methods on primitives

### ISSUE THREAD

**Issue by m4b** [mackwic/colored#22]
For a start `0xdeadbeef.red()` would be such an ergonomic gain I'd cry from happiness :)

**Comment by mackwic** [comment]
that's a nice idea ! Now that you say it, I'll do it for anything that implement `.toString()`. That should do for all primitives, right ?

**Comment by m4b** [comment]
Oh totally; in fact should be able to replace everything with single generic ToString bound :)

**Comment by m4b** [comment]
PS keep up the good work, :heart: this crate

**Comment by mackwic** [comment]
Follow-up: Sorry, not that easy to make a `impl<T : Display> Colorize for T` because `ColoredString` impl `Display` itself... which makes a conflicting impl without specialization.

I took the night to think on it, and decided to have manual impls for the primitives on stable, and a specialization on nightly.

Is this OK for you ?

**Comment by m4b** [comment]
Sure whatever is easiest for you! Unfortunately I realized I'm almost always printing hexadecimal numbers which still requires an extra call to format :/ don't know any way around it, either

**Comment by mackwic** [comment]
would you need a `.redf("format {:?}")` call which format your string and
put it red ?

**Comment by m4b** [comment]
Hmm, maybe; writing format in the string seems strange; why not just `redf.("{:#x}")`?

All that does it save me writing `format!("{:#x}").red()` iiuc, which is nice to be clear, but seems like a lot of work on your part for not a whole lot of gain.

**Comment by mackwic** [comment]
or `0xdeadbeef.to_hexa_string().red()` ?

Just thinking out loud about how we can make rust better. It can be a new crate

**Comment by m4b** [comment]
i mean i would love something like that (and i'm pretty disappointed sometimes by roughness around hexadecimal support in rust, ostensibly a "systems" language (see some examples below)), but I doubt anyone in a decision making position would see the value of adding something like that.  It's ok, I will just suffer :)

Alternatively of course, I can just add that method as a crate, as you suggested, but I probably won't get around to it, heh.

1. Can't (easily) print hexadecimal version of list of array of ints, vector, hashmap, etc.
2. It's obscure and weird (imho) to convert a string representing a number in hexadecimal form to the same numeric value
3. Can't (easily) print negative hexadecimal numbers

**Comment by mackwic** [comment]
Well, too bad. I thought the idea was cool, and I liked it. [So here it is](https://github.com/mackwic/to_string). It's published on crates.io if you want it.

```rust
let values = vec![ 12, 13, 14, 15 ];
let values : Vec<String> = values.into_iter().map(|e| e.to_bin().red()).collect();
println!("{:?}", values)
```

**Comment by m4b** [comment]
Well, that's great, thanks for publishing, I'll try it out! :)

I don't think I've ever used `UpperHex`, so this opinion is ok with me :)

So, it would be cool to not have to do

```rust
let values : Vec<String> = values.into_iter().map(|e| e.to_bin().red()).collect();
```

but instead 

```rust
let values : String = values.to_bin().red();
```

but this requires either specialization (this can't land fast enough imho), or impling them for numbers (which hexadecimal only exists for in std iirc), and then doing `for Vec<T> where T: HexaDisplay`

**Comment by mackwic** [comment]
Good idea. I'll look into it

**Comment by kylegalloway** [comment]
@mackwic @m4b can this be marked as closed for the colored repo?

**Comment by m4b** [comment]
Yea for sure if it was implemented, didn’t know that happened !

**Comment by kylegalloway** [comment]
It is not implemented for this repo. I thought by reading through the thread that it was going to be implemented in another crate.

**Comment by mackwic** [comment]
@kylegalloway you are right ! We can close this issue.

For reference, here is the working code:

```rust
extern crate to_string;
extern crate colored;

use to_string::*;
use colored::*;

fn main() {
   // will print "0xdeadbeef" on green
  println!("{}", (-559038737).to_hexa().green());
}
```
