### ISSUE TITLE
reverse vs. reversed

### ISSUE THREAD

**Issue by isaacg1** [mackwic/colored#23]
The method is `.reverse()`, while the object is `Styles::Reversed`. All of the other styles, including dimmed, have the same spelling in both cases. Moreover, the documentation does not mention the difference, as it only mentions reversed. This makes it very hard to discover the .reverse() method.

I would recommend adding the .reversed() method which does the same thing as .reverse(), or at least clarifying the situation in the documentation.

**Comment by mackwic** [comment]
Oh ! My bad you're right !

**Comment by mackwic** [comment]
This is fixed in the v1.5.2 version. Thanks to your comment, I also added a link in the main page of the documentation to the principal trait.

Thanks for your feedback. If you have any other suggestion or thing you'll wish to say, don't hesitate to say it here, or in another issue. :)

**Comment by isaacg1** [comment]
Thanks for the quick response!
