### ISSUE TITLE
non-bold yellow is brown

### ISSUE THREAD

**Issue by xftroxgpx** [mackwic/colored#24]
```rust
 println!("{} {} {} {}!",                                                    
             "it".green(),
             "works".blue().bold(),
             "great".bold().yellow(),
             "great".yellow()
             );
```

![untitled](https://user-images.githubusercontent.com/26243389/28295711-fa21bba8-6b62-11e7-8fd5-1ed984d14998.png)

`TERM` is `xterm-256color` but `linux` and `xterm` have the same effect.
tried in `xfce4-terminal` 0.8.6-1 on ArchLinux

oh crap i just realized why!
![screenshot_2017-07-18_02-46-47](https://user-images.githubusercontent.com/26243389/28295770-761e0fae-6b63-11e7-8390-e9f3bfbf5d64.png)

Nevermind! :)
I set it to yellow myself now, but the tooltip is interesting, why would it expect it to be somehow both?
![2untitled](https://user-images.githubusercontent.com/26243389/28295814-e8c3b626-6b63-11e7-871e-271434d05733.png)
![3untitled](https://user-images.githubusercontent.com/26243389/28295826-0add7b02-6b64-11e7-8bd8-a0bc134a1c67.png)

**Comment by mackwic** [comment]
Yes, the exact color is determined by the terminal emulator, and nowadays they all support profiles (except xterm and the like).

No idea why yellow/brown is put in tooltip, maybe some RFC somewhere said that bold yellow should be brown. Who knows ?

I am closing the issue. 😄

**Comment by xftroxgpx** [comment]
Thanks.
Small correction: the tooltip "Brown/Yellow" is for normal non-bold yellow, since the 'bold yellow' was initially correct (and has the "Yellow" tooltip).
Looks like the top row is for normal colors and the bottom row is for bold ones, in xfce4-terminal.
