### ISSUE TITLE
Dark grey color

### ISSUE THREAD

**Issue by pftbest** [mackwic/colored#25]
Hello!
I'm using this code `"\x1b[90m"` to create a dark grey color in the terminal.
How can I make such color using this library?

**Comment by kylegalloway** [comment]
This is fixed by PR #34. You can use it like this:
`"dark grey is bright black".bright_black();`

**Comment by pftbest** [comment]
Thanks!

**Comment by donaldpipowitch** [comment]
Cool. Maybe `bright_black` could be aliased to grey/gray? I just searched for it in the API and than found this issue :)
