### ISSUE TITLE
Tests fail to run due to rspec upgrade

### ISSUE THREAD

**Issue by Horgix** [mackwic/colored#29]
When I run a `cargo test` after cloning this repository, I get this:

```
   Compiling colored v1.5.2 (file:///...../colored)
error[E0432]: unresolved import `rspec::context::*`
  --> src/control.rs:95:9
   |
95 |     use rspec::context::*;
   |         ^^^^^^^^^^^^^^^^^^ Could not find `context` in `rspec`

error[E0433]: failed to resolve. Could not find `formatter` in `rspec`
   --> src/control.rs:105:29
    |
105 |         let mut formatter = rspec::formatter::Simple::new(stdout);
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `formatter` in `rspec`

error[E0425]: cannot find function `describe` in this scope
   --> src/control.rs:106:26
    |
106 |         let mut runner = describe("ShouldColorize", |ctx| {
    |                          ^^^^^^^^ not found in this scope
    |
help: possible candidates are found in other modules, you can import them into scope
    |     fn clicolor_behavior() use rspec::block::describe;
    |     fn clicolor_behavior() use rspec::describe;

error: aborting due to previous error(s)

error: Could not compile `colored`.
Build failed, waiting for other jobs to finish...
error: build failed
```

Travis build also fails due to this.

I might take a look at it if I find the time, but don't take this as a promise 🙂

**Comment by Horgix** [comment]
Looks like it's fetching rspec `v1.0.0-beta.4` even if `v1.0.0-beta.3` is given in the `Cargo.toml`. `master` branch was building fine 2 months ago with `v1.0.0-beta.3`

**Comment by Horgix** [comment]
No idea how to fix that since `rspec` lib essentially broke semantic versionning there, and `colored` shouldn't have the `Cargo.lock` embedded since it's just a lib.

Ping @mackwic since you're also the author of rspec ? 😉

**Comment by mackwic** [comment]
I thank you for reporting the bug. It's now fixed.

FYI, beta releases can break the public API. Semver is respected here. You should always depend on exact beta dependency (something I wasn't doing).
