### ISSUE TITLE
Windows 10+ supports ANSI codes

### ISSUE THREAD

**Issue by Fleshgrinder** [mackwic/colored#37]
Currently, it is stated everywhere that Windows support will be added in the future. I know how this is meant, you want to support older Windows consoles that do not have support for ANSI codes. However, it should be mentioned that recent Windows versions have full support for the coloring implementation of this crate, just to ensure that people are not running away frightened because they think that there is absolutely no coloring support on Windows.

https://blogs.msdn.microsoft.com/commandline/2016/09/22/24-bit-color-in-the-windows-console/

**Comment by mackwic** [comment]
thank you for bringing it ! I'll need to update the Readme...

**Comment by Hopson97** [comment]
Hello.

I can confirm this library works on Windows Powershell :)

However, it doesn't work on the old "cmd.exe", but that's outdated anyway so that's not an issue.

**Comment by Meeeeow** [comment]
It works on Windows PowerShell with `cargo run`, but print color codes when direct run the executable file

**Comment by kurtlawrence** [comment]
I have made a PR with a flag to make this work https://github.com/mackwic/colored/pull/47.

**Comment by mackwic** [comment]
PR has been merged 🎉 

Closing this issue. Please reopen in case of any issue.
