### ISSUE TITLE
New release with latest changes

### ISSUE THREAD

**Issue by discosultan** [mackwic/colored#41]
I'd like to request a new release of the package which would include the following changes: https://github.com/mackwic/colored/commit/3328890230ec99e3997c42cddc5d56dfc11f0c08 & https://github.com/mackwic/colored/commit/49584e5aff3431eae132831cb3c70e6573bd36cd.

Thanks!

**Comment by mackwic** [comment]
Version v1.6.1 has been published. 👌 

Thank for the reminder and for your patience. :)
