### ISSUE TITLE
Colours don't work in command prompt on Windows

### ISSUE THREAD

**Issue by woubuc** [mackwic/colored#56]
The colours are displayed as code in the standard command prompt on Windows 10.

What it looks like:
![image](https://user-images.githubusercontent.com/1015540/59136734-b8c33500-8984-11e9-8457-5e49e6c4e3bd.png)

What it should look like (using Cmder):
![image](https://user-images.githubusercontent.com/1015540/59136761-dd1f1180-8984-11e9-8bcf-f85e75cc39bc.png)

[Code used](https://github.com/woubuc/project-cleanup/blob/640bfe1fa4892f01be6f7045237e0081dd38058a/src/find_paths.rs#L80)

I know the cmd supports colours, since Cargo displays colours just fine.

**Comment by noxabellus** [comment]
Running my exe with this crate, in the integrated powershell terminal in vs code on windows, if I run via `cargo run`, the coloring works, however if I run the executable directly it does not

**Comment by noxabellus** [comment]
For what its worth, I added this to the top of my `main` and it works now: 
```rust
#[cfg(windows)] unsafe {
  let handle = winapi::um::processenv::GetStdHandle(winapi::um::winbase::STD_OUTPUT_HANDLE);
  let mut original_mode: winapi::shared::minwindef::DWORD = 0;
  winapi::um::consoleapi::GetConsoleMode(handle, &mut original_mode);
  winapi::um::consoleapi::SetConsoleMode(handle, winapi::um::wincon::ENABLE_VIRTUAL_TERMINAL_PROCESSING | original_mode);
}
```

**Comment by kurtlawrence** [comment]
Hi @noxabellus, there is already a function to do that: [`set_virtual_terminal`](https://docs.rs/colored/1.8.0/x86_64-pc-windows-msvc/colored/control/fn.set_virtual_terminal.html)

It doesn't show up in the docs unless you set the platform to windows
