### ISSUE TITLE
Commit 4af2de0 breaks coloring

### ISSUE THREAD

**Issue by klingtnet** [mackwic/colored#69]
I use `colored` in a small tool that generates my shell prompt ([rusty-prompt](https://github.com/klingtnet/dotfiles/tree/3195ab07a911c8d7582117d4aa3338cad15c1e79/tools/rusty-prompt)).
After updating colored from 1.8.0 to 1.9.0 I noticed that my shell prompt was not colored anymore, neither in bash nor in zsh. I then compiled rusty-prompt against all commits between 1.8.0 and 1.9.0 of colored and figured out that this commit broke the coloring for me: 4af2de0f095cc7a994d65e5d36dda60b7af25c82 .
The reason seems to be that `colored` now wrongly detects my terminal as TTY.

**Comment by kurtlawrence** [comment]
Hi @klingtnet 

Could you please run the examples at [atty](https://github.com/softprops/atty) and see what you get?

I cloned your repo, ran a `cargo update` and it is working fine for me, I tried both in bash and zsh, on ubuntu.

**Comment by klingtnet** [comment]
The examples run fine and rusty-prompt also has colors when run as a simple command but not when it is executed to generate the shell prompt: https://github.com/klingtnet/dotfiles/blob/02c2bacd31b255afac8ee6a69ffb8279e876bc70/dots/.bashrc#L17

**Comment by kurtlawrence** [comment]
Hi @klingtnet 

I see your issue now.

You can fix it by adding `colored::control::set_override(true);` to the top of your main function.

Below is my testing on your repo and it is working.

![image](https://user-images.githubusercontent.com/13831379/69103741-508f8800-0aba-11ea-8a44-2dac2979f8be.png)

**Comment by klingtnet** [comment]
Thank you very much, I can confirm that it works now!
