### ISSUE TITLE
no colored output when used in conjunction with package 'pager'

### ISSUE THREAD

**Issue by soenkehahn** [mackwic/colored#70]
When using the `colored` crate together with the `pager` crate it doesn't produce colored output.

Here's a repo that reproduces this behavior: https://github.com/soenkehahn/colored-bug
In there, `cargo run` should produce the word `foo` in red to stdout, but it's not red.

This used to work in version `1.8.0`. The commit where this stopped working seems to be this one: 4af2de0f095cc7a994d65e5d36dda60b7af25c82

**Comment by kurtlawrence** [comment]
Hi @soenkehahn,

This is similar to #69.

The most likely solution is to force colouring using `colored::control::set_override(true);`.

**Comment by soenkehahn** [comment]
Yes, that does it. Thanks!
