### ISSUE TITLE
How to use with std::io::stdout?

### ISSUE THREAD

**Issue by medakk** [mackwic/colored#89]
The library works fine when I am using `print!` or `println!`. But when writing to stdout, like:

```rust
let mut stdout = stdout();
let s = "Hello\n".truecolor(200, 50, 50);
stdout.write(s.as_bytes());
stdout.flush();
```

I see only regular black-and-white text. How do I get the library to work with stdout?

**Comment by medakk** [comment]
never mind, I figure it out:

```rust
stdout.write(s.to_string().as_bytes())
```

**Comment by spenserblack** [comment]
You might also want to check out the [`write!` macro](https://doc.rust-lang.org/std/macro.write.html).
This should work fine
```rust
write!(stdout, "{}", "Hello".truecolor(200, 50, 50));
```
