### ISSUE TITLE
Colored output for characters?

### ISSUE THREAD

**Issue by grtcdr** [mackwic/colored#92]
Is there any way we can color **characters** and not just strings?

**Comment by spenserblack** [comment]
Unless/until `colored::Colorize` is implemented directly on `char` in this crate, I think you will need to create a wrapper for a `char` and manually implement `Colorize` on it, or convert the `char` to a type that implements `Colorize`.

```rust
println!("red char: {}", 'r'.to_string().red());
```

**Comment by grtcdr** [comment]
I'll wait for #91 to get merged, thanks a lot!
